config/routes.rb
Rails.application.routes.draw do

  root :to => 'deck#index'
  get 'deck/index'

  get 'new_hands/:token' => 'deck#new_hands', :as => :new_hands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deck_controller.rb
class DeckController < ApplicationController
  def index
    dealer = Dealer.new
    @token = dealer.get_token
    @hand_one = dealer.get_cards(@token, 5)
    @hand_two = dealer.get_cards(@token, 5)
    @out_of_hands = "Session Deck Expired!" if  @hand_one == 404 or @hand_two == 404
    unless @out_of_hands
      winner = dealer.winner_hand(@hand_one, @hand_two)
      @winner_hand = winner.first
      @winner_hand_name = winner.last
    end
  end

  def new_hands
    dealer = Dealer.new
    @token = params[:token]
    @hand_one = dealer.get_cards(@token, 5)
    @hand_two = dealer.get_cards(@token, 5)
    @out_of_hands = "Session Deck Expired!" if  @hand_one == 404 or @hand_two == 404
    @out_of_hands = "Out of Hands!" if  @hand_one == 405 or @hand_two == 405
    unless @out_of_hands
      winner = dealer.winner_hand(@hand_one, @hand_two)
      @winner_hand = winner.first
      @winner_hand_name = winner.last
    end
    render 'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deck_helper.rb
module DeckHelper
end

app/views/deck/index.html.erb
<h1>Deck</h1>
<h1>Session: <%= @token %></h1>


<%= javascript_include_tag "deck" %>
<%= stylesheet_link_tag "deck", :media => 'screen' %>

<%= link_to "New Deck", root_path, html_options = {class: "btn"} %>

<% unless @out_of_hands %>
  <%= link_to "New Hand", new_hands_path(@token), html_options = {class: "btn"} %>
  <% if @winner_hand == 0%>
    <p>Is a Tie with <%= @winner_hand_name %>!!</p>
  <% else %>
    <p>Winner Hand <%= @winner_hand %>!! with <%= @winner_hand_name %></p>
  <% end %>

  <div class="hands">
    <h2>Mano 1</h2>
    <div class="hand grow ">
      <% @hand_one.each do |f| %>
        <div class="card suit<%=  f["suit"] %>">
          <p><%= f["number"]%></p>
        </div>  
      <% end %>
    </div>
    <h2>Mano 2</h2>
    <div class="hand grow ">
      <% @hand_two.each do |f| %>
        <div class="card suit<%=  f["suit"] %>">
          <p><%= f["number"]%></p>
        </div>  
      <% end %>
    </div>
  </div>

<% else %>
  <%= @out_of_hands %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poker</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>